#Application
spring.application.name=ecommerce


#DB
spring.datasource.url = jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username= root
spring.datasource.password = add_password_here

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

server.port = 8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Base path for Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# API documentation URL
springdoc.api-docs.path=/v3/api-docs

# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true

# Customize default URL for Swagger JSON
springdoc.swagger-ui.url=/v3/api-docs

# Enable deep linking for tags and operations
springdoc.swagger-ui.deep-linking=true

# Default expansion setting for operations and tags (list, full, none)
springdoc.swagger-ui.doc-expansion=none

# Enable "Try it out" feature by default
springdoc.swagger-ui.try-it-out-enabled=true

# Display request duration in "Try it out"
springdoc.swagger-ui.display-request-duration=true


jwt.secret = 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
